services:
    _defaults:
        autowire: true
        autoconfigure: true
    Yabx\RestBundle\EventSubscriber\ControllerArgumentsSubscriber: ~
    Yabx\RestBundle\EventSubscriber\ExceptionSubscriber: ~
    Yabx\RestBundle\EventSubscriber\RequestSubscriber: ~
    Yabx\RestBundle\EventSubscriber\ResponseSubscriber: ~
    Yabx\RestBundle\Service\ObjectBuilder: ~
    Yabx\RestBundle\Service\FieldsGroups: ~

